# Generated by Django 4.2.3 on 2023-07-25 21:18

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_category_name_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='manufacturer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_manufacrurer_name'),
        ),
    ]
