# Generated by Django 4.2.3 on 2023-07-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_manufacturer_unique_manufacrurer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
