# Generated by Django 4.2.3 on 2023-07-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_manufacturer_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='units',
            new_name='unit',
        ),
    ]
