# Generated by Django 4.2.3 on 2023-08-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_rename_units_unit_rename_units_storage_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='item_unit', to='storage.unit'),
            preserve_default=False,
        ),
    ]
