# Generated by Django 4.2.3 on 2023-08-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_item_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_number', models.CharField(max_length=250)),
                ('full_number', models.CharField(max_length=250, unique=True)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
