# Generated by Django 4.2.3 on 2023-08-29 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_item', to='storage.item'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_units', to='storage.unit'),
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_contract', to='storage.contract')),
            ],
        ),
    ]
