# Generated by Django 4.2.3 on 2023-09-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_storage_item_alter_storage_unit_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='storage',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='storage_contract', to='storage.contract'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemsInSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.item')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.supply')),
            ],
        ),
        migrations.AddField(
            model_name='supply',
            name='items',
            field=models.ManyToManyField(through='storage.ItemsInSupply', to='storage.item'),
        ),
    ]
