# Generated by Django 4.2.3 on 2023-09-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_company_staff_storage_contract_itemsinsupply_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemsInSupply',
            new_name='ItemInSupply',
        ),
        migrations.AlterUniqueTogether(
            name='storage',
            unique_together={('item', 'contract')},
        ),
    ]
