# Generated by Django 4.2.3 on 2023-09-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_rename_itemsinsupply_iteminsupply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='unit',
        ),
    ]
